apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.backend.image.port }}
  selector:
    server: {{ .Values.backend.name }}