apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      server: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        server: {{ .Values.frontend.name }}
    spec:
      containers:
        - name: {{ .Values.frontend.name }}
          image: {{ .Values.frontend.image.name }}:{{ .Values.frontend.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.frontend.image.port }}