apiVersion: v1
kind: Service
metadata:
  name: mongodbservice
  namespace: default
spec:
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: 27017
  type: ClusterIP
  selector:
    app: mongo