namespace: default

frontend:
  name: flask
  replicas: 1

  image:
    name: albird/flask
    tag: latest
    port: 8000

  nodeSelector:
    hardware: cloud
  
  service:
    name: flask
    type: ClusterIP

backend:
  name: flask-opencv
  replicas: 1

  image:
    name: albird/flask-opencv
    tag: latest
    port: 5000

  nodeSelector:
    hardware: premise

  tolerations:
    - key: "hardware"
      operator: "Equal"
      value: "cpu"
      effect: "NoSchedule"
  
  service:
    name: flask-opencv
    type: ClusterIP

auth:
  name: flask-auth
  replicas: 1

  image:
    name: albird/flask-auth
    tag: latest
    port: 5001

  nodeSelector:
    hardware: cloud

  service:
    name: flask-auth
    type: ClusterIP

opencvolume:
  skipuninstall: true
  persistence:
    claimName: opencv-images-claimdata
    volumeName: opencv-images-volume
    accessModes:
      - ReadWriteOnce
    storageClassName: local-path
    storage: 4Gi

mongodbvolume:
  persistence:
    claimName: pvc
    volumeName: pv
    accessModes:
      - ReadWriteOnce 
    storageClassName: local-path
    storage: 4Gi
