apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.image.port }}
      protocol: TCP
      name: http
  selector:
    server: {{ .Values.frontend.name }}