apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      server: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        server: {{ .Values.frontend.name }}
    spec:
      containers:
        - name: {{ .Values.frontend.name }}
          image: {{ .Values.frontend.image.name }}:{{ .Values.frontend.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.frontend.image.port }}
          env:
          - name: loginEndpoint
            value: https://labs.albert-hahn-apply.com/auth/login
          - name: registerEndpoint
            value: https://labs.albert-hahn-apply.com/auth/register
          - name: websocketServer
            value: https://labs.albert-hahn-apply.com
          - name: profileEndpoint
            value: https://labs.albert-hahn-apply.com/profile
      nodeSelector:
        hardware: {{ .Values.frontend.nodeSelector.hardware }}
