apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.face.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.face.service.type }}
  ports:
    - port: {{ .Values.face.image.port }}
      targetPort: {{ .Values.face.image.port }}
      protocol: TCP
      name: http
  selector:
    server: {{ .Values.face.name }}