apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.opencvolume.persistence.claimName }}
  annotations:
    {{- if .Values.skipuninstall }}
    "helm.sh/resource-policy": keep
    {{- end }}
spec:
  storageClassName: {{ .Values.opencvolume.persistence.storageClassName }}
  accessModes:
    {{- toYaml .Values.opencvolume.persistence.accessModes | nindent 4  }}
  resources:
    requests:
      storage: {{ .Values.opencvolume.persistence.storage }}