apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: flask-opencv
  name: flask-opencv
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flask-opencv
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: flask-opencv
    spec:
      containers:
        - args:
            - gunicorn
            - -k
            - geventwebsocket.gunicorn.workers.GeventWebSocketWorker
            - -w
            - "1"
            - -b
            - 0.0.0.0:5000
            - run:app
          image: albird/flask-opencv:latest
          name: flask-opencv
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
