apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: flask
  name: flask
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
    - name: 8000-tcp
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: flask
status:
  loadBalancer: {}
