#frontend section
build-frontend:
	cd frontend; \
	docker build -t albird/frontend:latest . 

push-frontend:
	cd frontend; \
	docker push albird/frontend:latest

build-push-frontend:
	cd frontend; \
	docker build -t albird/frontend:latest .; \
	docker push albird/frontend:latest

#facerecognition section
build-facerecognition:
	cd facerecognition; \
	docker build -t albird/facerecognition:latest . 

push-facerecognition:
	cd facerecognition; \
	docker push albird/facerecognition:latest

build-push-facerecognition:
	cd facerecognition; \
	docker build -t albird/facerecognition:latest .; \
	docker push albird/facerecognition:latest

#authentication section
build-authentication:
	cd authentication; \
	docker build -t albird/authenticationlatest . 

push-authentication:
	cd authentication; \
	docker push albird/authentication:latest

build-push-authentication:
	cd authentication; \
	docker build -t albird/authentication:latest .; \
	docker push albird/authentication:latest